//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccelerationStatus) DeepCopyInto(out *AccelerationStatus) {
	*out = *in
	if in.LayersOffloaded != nil {
		in, out := &in.LayersOffloaded, &out.LayersOffloaded
		*out = new(int32)
		**out = **in
	}
	if in.LayersTotal != nil {
		in, out := &in.LayersTotal, &out.LayersTotal
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccelerationStatus.
func (in *AccelerationStatus) DeepCopy() *AccelerationStatus {
	if in == nil {
		return nil
	}
	out := new(AccelerationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentGatewayReference) DeepCopyInto(out *AgentGatewayReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentGatewayReference.
func (in *AgentGatewayReference) DeepCopy() *AgentGatewayReference {
	if in == nil {
		return nil
	}
	out := new(AgentGatewayReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentGatewayStatus) DeepCopyInto(out *AgentGatewayStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentGatewayStatus.
func (in *AgentGatewayStatus) DeepCopy() *AgentGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(AgentGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLogPolicy) DeepCopyInto(out *AuditLogPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLogPolicy.
func (in *AuditLogPolicy) DeepCopy() *AuditLogPolicy {
	if in == nil {
		return nil
	}
	out := new(AuditLogPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingSpec) DeepCopyInto(out *AutoscalingSpec) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]MetricSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingSpec.
func (in *AutoscalingSpec) DeepCopy() *AutoscalingSpec {
	if in == nil {
		return nil
	}
	out := new(AutoscalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendHealthCheck) DeepCopyInto(out *BackendHealthCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendHealthCheck.
func (in *BackendHealthCheck) DeepCopy() *BackendHealthCheck {
	if in == nil {
		return nil
	}
	out := new(BackendHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendStatus) DeepCopyInto(out *BackendStatus) {
	*out = *in
	if in.LastProbeTime != nil {
		in, out := &in.LastProbeTime, &out.LastProbeTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendStatus.
func (in *BackendStatus) DeepCopy() *BackendStatus {
	if in == nil {
		return nil
	}
	out := new(BackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetSpec) DeepCopyInto(out *BudgetSpec) {
	*out = *in
	if in.MaxTokens != nil {
		in, out := &in.MaxTokens, &out.MaxTokens
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetSpec.
func (in *BudgetSpec) DeepCopy() *BudgetSpec {
	if in == nil {
		return nil
	}
	out := new(BudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetStatus) DeepCopyInto(out *BudgetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetStatus.
func (in *BudgetStatus) DeepCopy() *BudgetStatus {
	if in == nil {
		return nil
	}
	out := new(BudgetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClassificationPolicy) DeepCopyInto(out *ClassificationPolicy) {
	*out = *in
	if in.SensitiveClassifications != nil {
		in, out := &in.SensitiveClassifications, &out.SensitiveClassifications
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClassificationPolicy.
func (in *ClassificationPolicy) DeepCopy() *ClassificationPolicy {
	if in == nil {
		return nil
	}
	out := new(ClassificationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisruptionSpec) DeepCopyInto(out *DisruptionSpec) {
	*out = *in
	if in.ProtectStartup != nil {
		in, out := &in.ProtectStartup, &out.ProtectStartup
		*out = new(bool)
		**out = **in
	}
	if in.ProtectAlways != nil {
		in, out := &in.ProtectAlways, &out.ProtectAlways
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisruptionSpec.
func (in *DisruptionSpec) DeepCopy() *DisruptionSpec {
	if in == nil {
		return nil
	}
	out := new(DisruptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointSpec) DeepCopyInto(out *EndpointSpec) {
	*out = *in
	if in.NodePort != nil {
		in, out := &in.NodePort, &out.NodePort
		*out = new(int32)
		**out = **in
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(GatewaySpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointSpec.
func (in *EndpointSpec) DeepCopy() *EndpointSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalProvider) DeepCopyInto(out *ExternalProvider) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalProvider.
func (in *ExternalProvider) DeepCopy() *ExternalProvider {
	if in == nil {
		return nil
	}
	out := new(ExternalProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GGUFMetadata) DeepCopyInto(out *GGUFMetadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GGUFMetadata.
func (in *GGUFMetadata) DeepCopy() *GGUFMetadata {
	if in == nil {
		return nil
	}
	out := new(GGUFMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUQuota) DeepCopyInto(out *GPUQuota) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUQuota.
func (in *GPUQuota) DeepCopy() *GPUQuota {
	if in == nil {
		return nil
	}
	out := new(GPUQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUQuota) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUQuotaList) DeepCopyInto(out *GPUQuotaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUQuota, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUQuotaList.
func (in *GPUQuotaList) DeepCopy() *GPUQuotaList {
	if in == nil {
		return nil
	}
	out := new(GPUQuotaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUQuotaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUQuotaSpec) DeepCopyInto(out *GPUQuotaSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUQuotaSpec.
func (in *GPUQuotaSpec) DeepCopy() *GPUQuotaSpec {
	if in == nil {
		return nil
	}
	out := new(GPUQuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUQuotaStatus) DeepCopyInto(out *GPUQuotaStatus) {
	*out = *in
	if in.LastDenial != nil {
		in, out := &in.LastDenial, &out.LastDenial
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUQuotaStatus.
func (in *GPUQuotaStatus) DeepCopy() *GPUQuotaStatus {
	if in == nil {
		return nil
	}
	out := new(GPUQuotaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUShardingSpec) DeepCopyInto(out *GPUShardingSpec) {
	*out = *in
	if in.LayerSplit != nil {
		in, out := &in.LayerSplit, &out.LayerSplit
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUShardingSpec.
func (in *GPUShardingSpec) DeepCopy() *GPUShardingSpec {
	if in == nil {
		return nil
	}
	out := new(GPUShardingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUSharingSpec) DeepCopyInto(out *GPUSharingSpec) {
	*out = *in
	if in.MemoryLimitGiB != nil {
		in, out := &in.MemoryLimitGiB, &out.MemoryLimitGiB
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUSharingSpec.
func (in *GPUSharingSpec) DeepCopy() *GPUSharingSpec {
	if in == nil {
		return nil
	}
	out := new(GPUSharingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUSpec) DeepCopyInto(out *GPUSpec) {
	*out = *in
	if in.Sharding != nil {
		in, out := &in.Sharding, &out.Sharding
		*out = new(GPUShardingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceClaims != nil {
		in, out := &in.ResourceClaims, &out.ResourceClaims
		*out = make([]corev1.PodResourceClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUSpec.
func (in *GPUSpec) DeepCopy() *GPUSpec {
	if in == nil {
		return nil
	}
	out := new(GPUSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayReference) DeepCopyInto(out *GatewayReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayReference.
func (in *GatewayReference) DeepCopy() *GatewayReference {
	if in == nil {
		return nil
	}
	out := new(GatewayReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaySpec) DeepCopyInto(out *GatewaySpec) {
	*out = *in
	out.GatewayRef = in.GatewayRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaySpec.
func (in *GatewaySpec) DeepCopy() *GatewaySpec {
	if in == nil {
		return nil
	}
	out := new(GatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayStatus) DeepCopyInto(out *GatewayStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayStatus.
func (in *GatewayStatus) DeepCopy() *GatewayStatus {
	if in == nil {
		return nil
	}
	out := new(GatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardwareSpec) DeepCopyInto(out *HardwareSpec) {
	*out = *in
	if in.GPU != nil {
		in, out := &in.GPU, &out.GPU
		*out = new(GPUSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MemoryFraction != nil {
		in, out := &in.MemoryFraction, &out.MemoryFraction
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardwareSpec.
func (in *HardwareSpec) DeepCopy() *HardwareSpec {
	if in == nil {
		return nil
	}
	out := new(HardwareSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceResourceRequirements) DeepCopyInto(out *InferenceResourceRequirements) {
	*out = *in
	if in.GPUSharing != nil {
		in, out := &in.GPUSharing, &out.GPUSharing
		*out = new(GPUSharingSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceResourceRequirements.
func (in *InferenceResourceRequirements) DeepCopy() *InferenceResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(InferenceResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceService) DeepCopyInto(out *InferenceService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceService.
func (in *InferenceService) DeepCopy() *InferenceService {
	if in == nil {
		return nil
	}
	out := new(InferenceService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferenceService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceServiceList) DeepCopyInto(out *InferenceServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InferenceService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceServiceList.
func (in *InferenceServiceList) DeepCopy() *InferenceServiceList {
	if in == nil {
		return nil
	}
	out := new(InferenceServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferenceServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceServiceSpec) DeepCopyInto(out *InferenceServiceSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.RevisionHistoryLimit != nil {
		in, out := &in.RevisionHistoryLimit, &out.RevisionHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(AutoscalingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(EndpointSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(InferenceResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]corev1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.RuntimeClassName != nil {
		in, out := &in.RuntimeClassName, &out.RuntimeClassName
		*out = new(string)
		**out = **in
	}
	if in.ContextSize != nil {
		in, out := &in.ContextSize, &out.ContextSize
		*out = new(int32)
		**out = **in
	}
	if in.RopeScaling != nil {
		in, out := &in.RopeScaling, &out.RopeScaling
		*out = new(RopeScalingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ParallelSlots != nil {
		in, out := &in.ParallelSlots, &out.ParallelSlots
		*out = new(int32)
		**out = **in
	}
	if in.FlashAttention != nil {
		in, out := &in.FlashAttention, &out.FlashAttention
		*out = new(bool)
		**out = **in
	}
	if in.Jinja != nil {
		in, out := &in.Jinja, &out.Jinja
		*out = new(bool)
		**out = **in
	}
	if in.MoeCPUOffload != nil {
		in, out := &in.MoeCPUOffload, &out.MoeCPUOffload
		*out = new(bool)
		**out = **in
	}
	if in.MoeCPULayers != nil {
		in, out := &in.MoeCPULayers, &out.MoeCPULayers
		*out = new(int32)
		**out = **in
	}
	if in.NoKvOffload != nil {
		in, out := &in.NoKvOffload, &out.NoKvOffload
		*out = new(bool)
		**out = **in
	}
	if in.NoWarmup != nil {
		in, out := &in.NoWarmup, &out.NoWarmup
		*out = new(bool)
		**out = **in
	}
	if in.SpeculativeDecoding != nil {
		in, out := &in.SpeculativeDecoding, &out.SpeculativeDecoding
		*out = new(SpeculativeDecodingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ReasoningBudget != nil {
		in, out := &in.ReasoningBudget, &out.ReasoningBudget
		*out = new(int32)
		**out = **in
	}
	if in.MetadataOverrides != nil {
		in, out := &in.MetadataOverrides, &out.MetadataOverrides
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TensorOverrides != nil {
		in, out := &in.TensorOverrides, &out.TensorOverrides
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int32)
		**out = **in
	}
	if in.UBatchSize != nil {
		in, out := &in.UBatchSize, &out.UBatchSize
		*out = new(int32)
		**out = **in
	}
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TurboQuantBits != nil {
		in, out := &in.TurboQuantBits, &out.TurboQuantBits
		*out = new(int32)
		**out = **in
	}
	if in.PagedSSDCacheDir != nil {
		in, out := &in.PagedSSDCacheDir, &out.PagedSSDCacheDir
		*out = new(string)
		**out = **in
	}
	if in.HotCacheMaxSize != nil {
		in, out := &in.HotCacheMaxSize, &out.HotCacheMaxSize
		*out = new(string)
		**out = **in
	}
	if in.PagedSSDCacheMaxSize != nil {
		in, out := &in.PagedSSDCacheMaxSize, &out.PagedSSDCacheMaxSize
		*out = new(string)
		**out = **in
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraVolumes != nil {
		in, out := &in.ExtraVolumes, &out.ExtraVolumes
		*out = make([]corev1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraVolumeMounts != nil {
		in, out := &in.ExtraVolumeMounts, &out.ExtraVolumeMounts
		*out = make([]corev1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ContainerPort != nil {
		in, out := &in.ContainerPort, &out.ContainerPort
		*out = new(int32)
		**out = **in
	}
	if in.ProbeOverrides != nil {
		in, out := &in.ProbeOverrides, &out.ProbeOverrides
		*out = new(ProbeOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.SkipModelInit != nil {
		in, out := &in.SkipModelInit, &out.SkipModelInit
		*out = new(bool)
		**out = **in
	}
	if in.ModelCache != nil {
		in, out := &in.ModelCache, &out.ModelCache
		*out = new(ModelCacheSpec)
		**out = **in
	}
	if in.MultiNode != nil {
		in, out := &in.MultiNode, &out.MultiNode
		*out = new(MultiNodeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PersonaPlexConfig != nil {
		in, out := &in.PersonaPlexConfig, &out.PersonaPlexConfig
		*out = new(PersonaPlexConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.VLLMConfig != nil {
		in, out := &in.VLLMConfig, &out.VLLMConfig
		*out = new(VLLMConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TGIConfig != nil {
		in, out := &in.TGIConfig, &out.TGIConfig
		*out = new(TGIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SGLangConfig != nil {
		in, out := &in.SGLangConfig, &out.SGLangConfig
		*out = new(SGLangConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.EvictionProtection != nil {
		in, out := &in.EvictionProtection, &out.EvictionProtection
		*out = new(bool)
		**out = **in
	}
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(corev1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.Disruption != nil {
		in, out := &in.Disruption, &out.Disruption
		*out = new(DisruptionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RolloutPolicy != nil {
		in, out := &in.RolloutPolicy, &out.RolloutPolicy
		*out = new(RolloutPolicySpec)
		**out = **in
	}
	if in.SLO != nil {
		in, out := &in.SLO, &out.SLO
		*out = new(SLOSpec)
		**out = **in
	}
	if in.MaxPodLifetimeSeconds != nil {
		in, out := &in.MaxPodLifetimeSeconds, &out.MaxPodLifetimeSeconds
		*out = new(int64)
		**out = **in
	}
	if in.MaxPodLifetimeIdleTimeoutSeconds != nil {
		in, out := &in.MaxPodLifetimeIdleTimeoutSeconds, &out.MaxPodLifetimeIdleTimeoutSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceServiceSpec.
func (in *InferenceServiceSpec) DeepCopy() *InferenceServiceSpec {
	if in == nil {
		return nil
	}
	out := new(InferenceServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceServiceStatus) DeepCopyInto(out *InferenceServiceStatus) {
	*out = *in
	if in.Acceleration != nil {
		in, out := &in.Acceleration, &out.Acceleration
		*out = new(AccelerationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(GatewayStatus)
		**out = **in
	}
	if in.MultiNode != nil {
		in, out := &in.MultiNode, &out.MultiNode
		*out = new(MultiNodeStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceServiceStatus.
func (in *InferenceServiceStatus) DeepCopy() *InferenceServiceStatus {
	if in == nil {
		return nil
	}
	out := new(InferenceServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWTAuthSpec) DeepCopyInto(out *JWTAuthSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWTAuthSpec.
func (in *JWTAuthSpec) DeepCopy() *JWTAuthSpec {
	if in == nil {
		return nil
	}
	out := new(JWTAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoRAAdapter) DeepCopyInto(out *LoRAAdapter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoRAAdapter.
func (in *LoRAAdapter) DeepCopy() *LoRAAdapter {
	if in == nil {
		return nil
	}
	out := new(LoRAAdapter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoRAAdapter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoRAAdapterList) DeepCopyInto(out *LoRAAdapterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoRAAdapter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoRAAdapterList.
func (in *LoRAAdapterList) DeepCopy() *LoRAAdapterList {
	if in == nil {
		return nil
	}
	out := new(LoRAAdapterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoRAAdapterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoRAAdapterSpec) DeepCopyInto(out *LoRAAdapterSpec) {
	*out = *in
	in.InferenceServiceRef.DeepCopyInto(&out.InferenceServiceRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoRAAdapterSpec.
func (in *LoRAAdapterSpec) DeepCopy() *LoRAAdapterSpec {
	if in == nil {
		return nil
	}
	out := new(LoRAAdapterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoRAAdapterStatus) DeepCopyInto(out *LoRAAdapterStatus) {
	*out = *in
	if in.LastLoadedAt != nil {
		in, out := &in.LastLoadedAt, &out.LastLoadedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoRAAdapterStatus.
func (in *LoRAAdapterStatus) DeepCopy() *LoRAAdapterStatus {
	if in == nil {
		return nil
	}
	out := new(LoRAAdapterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalInferenceServiceReference) DeepCopyInto(out *LocalInferenceServiceReference) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalInferenceServiceReference.
func (in *LocalInferenceServiceReference) DeepCopy() *LocalInferenceServiceReference {
	if in == nil {
		return nil
	}
	out := new(LocalInferenceServiceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerSpec) DeepCopyInto(out *MCPServerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerSpec.
func (in *MCPServerSpec) DeepCopy() *MCPServerSpec {
	if in == nil {
		return nil
	}
	out := new(MCPServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSpec) DeepCopyInto(out *MetricSpec) {
	*out = *in
	if in.TargetAverageValue != nil {
		in, out := &in.TargetAverageValue, &out.TargetAverageValue
		*out = new(string)
		**out = **in
	}
	if in.TargetAverageUtilization != nil {
		in, out := &in.TargetAverageUtilization, &out.TargetAverageUtilization
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSpec.
func (in *MetricSpec) DeepCopy() *MetricSpec {
	if in == nil {
		return nil
	}
	out := new(MetricSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Model) DeepCopyInto(out *Model) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Model.
func (in *Model) DeepCopy() *Model {
	if in == nil {
		return nil
	}
	out := new(Model)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Model) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCacheSpec) DeepCopyInto(out *ModelCacheSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCacheSpec.
func (in *ModelCacheSpec) DeepCopy() *ModelCacheSpec {
	if in == nil {
		return nil
	}
	out := new(ModelCacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelList) DeepCopyInto(out *ModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Model, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelList.
func (in *ModelList) DeepCopy() *ModelList {
	if in == nil {
		return nil
	}
	out := new(ModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelPool) DeepCopyInto(out *ModelPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelPool.
func (in *ModelPool) DeepCopy() *ModelPool {
	if in == nil {
		return nil
	}
	out := new(ModelPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelPoolList) DeepCopyInto(out *ModelPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelPoolList.
func (in *ModelPoolList) DeepCopy() *ModelPoolList {
	if in == nil {
		return nil
	}
	out := new(ModelPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelPoolMember) DeepCopyInto(out *ModelPoolMember) {
	*out = *in
	out.InferenceServiceRef = in.InferenceServiceRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelPoolMember.
func (in *ModelPoolMember) DeepCopy() *ModelPoolMember {
	if in == nil {
		return nil
	}
	out := new(ModelPoolMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelPoolMemberStatus) DeepCopyInto(out *ModelPoolMemberStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelPoolMemberStatus.
func (in *ModelPoolMemberStatus) DeepCopy() *ModelPoolMemberStatus {
	if in == nil {
		return nil
	}
	out := new(ModelPoolMemberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelPoolSpec) DeepCopyInto(out *ModelPoolSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]ModelPoolMember, len(*in))
		copy(*out, *in)
	}
	if in.SwapBudget != nil {
		in, out := &in.SwapBudget, &out.SwapBudget
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ReclaimAfter != nil {
		in, out := &in.ReclaimAfter, &out.ReclaimAfter
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelPoolSpec.
func (in *ModelPoolSpec) DeepCopy() *ModelPoolSpec {
	if in == nil {
		return nil
	}
	out := new(ModelPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelPoolStatus) DeepCopyInto(out *ModelPoolStatus) {
	*out = *in
	if in.ResidentIdleSince != nil {
		in, out := &in.ResidentIdleSince, &out.ResidentIdleSince
		*out = (*in).DeepCopy()
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]ModelPoolMemberStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelPoolStatus.
func (in *ModelPoolStatus) DeepCopy() *ModelPoolStatus {
	if in == nil {
		return nil
	}
	out := new(ModelPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRouter) DeepCopyInto(out *ModelRouter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRouter.
func (in *ModelRouter) DeepCopy() *ModelRouter {
	if in == nil {
		return nil
	}
	out := new(ModelRouter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelRouter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRouterList) DeepCopyInto(out *ModelRouterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelRouter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRouterList.
func (in *ModelRouterList) DeepCopy() *ModelRouterList {
	if in == nil {
		return nil
	}
	out := new(ModelRouterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelRouterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRouterSpec) DeepCopyInto(out *ModelRouterSpec) {
	*out = *in
	if in.GatewayRef != nil {
		in, out := &in.GatewayRef, &out.GatewayRef
		*out = new(GatewayReference)
		**out = **in
	}
	if in.AgentGatewayRef != nil {
		in, out := &in.AgentGatewayRef, &out.AgentGatewayRef
		*out = new(AgentGatewayReference)
		**out = **in
	}
	if in.Backends != nil {
		in, out := &in.Backends, &out.Backends
		*out = make([]RouterBackend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]RouterRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(RouterPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(EndpointSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(RouterProxySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MCPServer != nil {
		in, out := &in.MCPServer, &out.MCPServer
		*out = new(MCPServerSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRouterSpec.
func (in *ModelRouterSpec) DeepCopy() *ModelRouterSpec {
	if in == nil {
		return nil
	}
	out := new(ModelRouterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRouterStatus) DeepCopyInto(out *ModelRouterStatus) {
	*out = *in
	if in.Backends != nil {
		in, out := &in.Backends, &out.Backends
		*out = make([]BackendStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BudgetUtilization != nil {
		in, out := &in.BudgetUtilization, &out.BudgetUtilization
		*out = make([]BudgetStatus, len(*in))
		copy(*out, *in)
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(GatewayStatus)
		**out = **in
	}
	if in.AgentGateway != nil {
		in, out := &in.AgentGateway, &out.AgentGateway
		*out = new(AgentGatewayStatus)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRouterStatus.
func (in *ModelRouterStatus) DeepCopy() *ModelRouterStatus {
	if in == nil {
		return nil
	}
	out := new(ModelRouterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSpec) DeepCopyInto(out *ModelSpec) {
	*out = *in
	if in.SourceSecretRef != nil {
		in, out := &in.SourceSecretRef, &out.SourceSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.PrefetchTolerations != nil {
		in, out := &in.PrefetchTolerations, &out.PrefetchTolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Hardware != nil {
		in, out := &in.Hardware, &out.Hardware
		*out = new(HardwareSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		**out = **in
	}
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSpec.
func (in *ModelSpec) DeepCopy() *ModelSpec {
	if in == nil {
		return nil
	}
	out := new(ModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelStatus) DeepCopyInto(out *ModelStatus) {
	*out = *in
	if in.StagedFiles != nil {
		in, out := &in.StagedFiles, &out.StagedFiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastRevalidated != nil {
		in, out := &in.LastRevalidated, &out.LastRevalidated
		*out = (*in).DeepCopy()
	}
	if in.GGUF != nil {
		in, out := &in.GGUF, &out.GGUF
		*out = new(GGUFMetadata)
		**out = **in
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelStatus.
func (in *ModelStatus) DeepCopy() *ModelStatus {
	if in == nil {
		return nil
	}
	out := new(ModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiNodeMember) DeepCopyInto(out *MultiNodeMember) {
	*out = *in
	if in.Fabric != nil {
		in, out := &in.Fabric, &out.Fabric
		*out = new(MultiNodeMemberFabric)
		**out = **in
	}
	if in.ModelCache != nil {
		in, out := &in.ModelCache, &out.ModelCache
		*out = new(MultiNodeMemberCache)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiNodeMember.
func (in *MultiNodeMember) DeepCopy() *MultiNodeMember {
	if in == nil {
		return nil
	}
	out := new(MultiNodeMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiNodeMemberCache) DeepCopyInto(out *MultiNodeMemberCache) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiNodeMemberCache.
func (in *MultiNodeMemberCache) DeepCopy() *MultiNodeMemberCache {
	if in == nil {
		return nil
	}
	out := new(MultiNodeMemberCache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiNodeMemberFabric) DeepCopyInto(out *MultiNodeMemberFabric) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiNodeMemberFabric.
func (in *MultiNodeMemberFabric) DeepCopy() *MultiNodeMemberFabric {
	if in == nil {
		return nil
	}
	out := new(MultiNodeMemberFabric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiNodeMemberStatus) DeepCopyInto(out *MultiNodeMemberStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiNodeMemberStatus.
func (in *MultiNodeMemberStatus) DeepCopy() *MultiNodeMemberStatus {
	if in == nil {
		return nil
	}
	out := new(MultiNodeMemberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiNodeSpec) DeepCopyInto(out *MultiNodeSpec) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]MultiNodeMember, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IBGIDIndex != nil {
		in, out := &in.IBGIDIndex, &out.IBGIDIndex
		*out = new(int32)
		**out = **in
	}
	if in.RendezvousPort != nil {
		in, out := &in.RendezvousPort, &out.RendezvousPort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiNodeSpec.
func (in *MultiNodeSpec) DeepCopy() *MultiNodeSpec {
	if in == nil {
		return nil
	}
	out := new(MultiNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiNodeStatus) DeepCopyInto(out *MultiNodeStatus) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]MultiNodeMemberStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiNodeStatus.
func (in *MultiNodeStatus) DeepCopy() *MultiNodeStatus {
	if in == nil {
		return nil
	}
	out := new(MultiNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersonaPlexConfig) DeepCopyInto(out *PersonaPlexConfig) {
	*out = *in
	if in.Quantize4Bit != nil {
		in, out := &in.Quantize4Bit, &out.Quantize4Bit
		*out = new(bool)
		**out = **in
	}
	if in.CPUOffload != nil {
		in, out := &in.CPUOffload, &out.CPUOffload
		*out = new(bool)
		**out = **in
	}
	if in.HFTokenSecretRef != nil {
		in, out := &in.HFTokenSecretRef, &out.HFTokenSecretRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersonaPlexConfig.
func (in *PersonaPlexConfig) DeepCopy() *PersonaPlexConfig {
	if in == nil {
		return nil
	}
	out := new(PersonaPlexConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeOverrides) DeepCopyInto(out *ProbeOverrides) {
	*out = *in
	if in.Startup != nil {
		in, out := &in.Startup, &out.Startup
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.Liveness != nil {
		in, out := &in.Liveness, &out.Liveness
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.Readiness != nil {
		in, out := &in.Readiness, &out.Readiness
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeOverrides.
func (in *ProbeOverrides) DeepCopy() *ProbeOverrides {
	if in == nil {
		return nil
	}
	out := new(ProbeOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequirements) DeepCopyInto(out *ResourceRequirements) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequirements.
func (in *ResourceRequirements) DeepCopy() *ResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutPolicySpec) DeepCopyInto(out *RolloutPolicySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutPolicySpec.
func (in *RolloutPolicySpec) DeepCopy() *RolloutPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RolloutPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RopeScalingSpec) DeepCopyInto(out *RopeScalingSpec) {
	*out = *in
	if in.OriginalContext != nil {
		in, out := &in.OriginalContext, &out.OriginalContext
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RopeScalingSpec.
func (in *RopeScalingSpec) DeepCopy() *RopeScalingSpec {
	if in == nil {
		return nil
	}
	out := new(RopeScalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterAuthSpec) DeepCopyInto(out *RouterAuthSpec) {
	*out = *in
	if in.JWT != nil {
		in, out := &in.JWT, &out.JWT
		*out = new(JWTAuthSpec)
		**out = **in
	}
	if in.Allowlists != nil {
		in, out := &in.Allowlists, &out.Allowlists
		*out = make([]TeamModelAllowlist, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterAuthSpec.
func (in *RouterAuthSpec) DeepCopy() *RouterAuthSpec {
	if in == nil {
		return nil
	}
	out := new(RouterAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterBackend) DeepCopyInto(out *RouterBackend) {
	*out = *in
	if in.InferenceServiceRef != nil {
		in, out := &in.InferenceServiceRef, &out.InferenceServiceRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(int32)
		**out = **in
	}
	if in.CostPerMillionTokens != nil {
		in, out := &in.CostPerMillionTokens, &out.CostPerMillionTokens
		*out = new(TokenCost)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(BackendHealthCheck)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterBackend.
func (in *RouterBackend) DeepCopy() *RouterBackend {
	if in == nil {
		return nil
	}
	out := new(RouterBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterPolicy) DeepCopyInto(out *RouterPolicy) {
	*out = *in
	if in.Budgets != nil {
		in, out := &in.Budgets, &out.Budgets
		*out = make([]BudgetSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Classification != nil {
		in, out := &in.Classification, &out.Classification
		*out = new(ClassificationPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.AuditLog != nil {
		in, out := &in.AuditLog, &out.AuditLog
		*out = new(AuditLogPolicy)
		**out = **in
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(RouterAuthSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterPolicy.
func (in *RouterPolicy) DeepCopy() *RouterPolicy {
	if in == nil {
		return nil
	}
	out := new(RouterPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterProxySpec) DeepCopyInto(out *RouterProxySpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.RevisionHistoryLimit != nil {
		in, out := &in.RevisionHistoryLimit, &out.RevisionHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.QuarantineDuration != nil {
		in, out := &in.QuarantineDuration, &out.QuarantineDuration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ResponseHeaderTimeout != nil {
		in, out := &in.ResponseHeaderTimeout, &out.ResponseHeaderTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterProxySpec.
func (in *RouterProxySpec) DeepCopy() *RouterProxySpec {
	if in == nil {
		return nil
	}
	out := new(RouterProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterRule) DeepCopyInto(out *RouterRule) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = new(RuleMatch)
		(*in).DeepCopyInto(*out)
	}
	in.Route.DeepCopyInto(&out.Route)
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterRule.
func (in *RouterRule) DeepCopy() *RouterRule {
	if in == nil {
		return nil
	}
	out := new(RouterRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleMatch) DeepCopyInto(out *RuleMatch) {
	*out = *in
	if in.DataClassification != nil {
		in, out := &in.DataClassification, &out.DataClassification
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequiredCapabilities != nil {
		in, out := &in.RequiredCapabilities, &out.RequiredCapabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LatencySLOMs != nil {
		in, out := &in.LatencySLOMs, &out.LatencySLOMs
		*out = new(int32)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleMatch.
func (in *RuleMatch) DeepCopy() *RuleMatch {
	if in == nil {
		return nil
	}
	out := new(RuleMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleRoute) DeepCopyInto(out *RuleRoute) {
	*out = *in
	if in.Backends != nil {
		in, out := &in.Backends, &out.Backends
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleRoute.
func (in *RuleRoute) DeepCopy() *RuleRoute {
	if in == nil {
		return nil
	}
	out := new(RuleRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGLangConfig) DeepCopyInto(out *SGLangConfig) {
	*out = *in
	if in.TensorParallelSize != nil {
		in, out := &in.TensorParallelSize, &out.TensorParallelSize
		*out = new(int32)
		**out = **in
	}
	if in.ExpertParallelSize != nil {
		in, out := &in.ExpertParallelSize, &out.ExpertParallelSize
		*out = new(int32)
		**out = **in
	}
	if in.DataParallelSize != nil {
		in, out := &in.DataParallelSize, &out.DataParallelSize
		*out = new(int32)
		**out = **in
	}
	if in.ContextLength != nil {
		in, out := &in.ContextLength, &out.ContextLength
		*out = new(int32)
		**out = **in
	}
	if in.MemFractionStatic != nil {
		in, out := &in.MemFractionStatic, &out.MemFractionStatic
		*out = new(float64)
		**out = **in
	}
	if in.ChunkedPrefillSize != nil {
		in, out := &in.ChunkedPrefillSize, &out.ChunkedPrefillSize
		*out = new(int32)
		**out = **in
	}
	if in.MaxRunningRequests != nil {
		in, out := &in.MaxRunningRequests, &out.MaxRunningRequests
		*out = new(int32)
		**out = **in
	}
	if in.KVCacheDtype != nil {
		in, out := &in.KVCacheDtype, &out.KVCacheDtype
		*out = new(string)
		**out = **in
	}
	if in.EnablePrefixCaching != nil {
		in, out := &in.EnablePrefixCaching, &out.EnablePrefixCaching
		*out = new(bool)
		**out = **in
	}
	if in.Speculative != nil {
		in, out := &in.Speculative, &out.Speculative
		*out = new(SGLangSpeculativeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.LoraModules != nil {
		in, out := &in.LoraModules, &out.LoraModules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxLoraRank != nil {
		in, out := &in.MaxLoraRank, &out.MaxLoraRank
		*out = new(int32)
		**out = **in
	}
	if in.LoraTargetModules != nil {
		in, out := &in.LoraTargetModules, &out.LoraTargetModules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LoraAdapters != nil {
		in, out := &in.LoraAdapters, &out.LoraAdapters
		*out = make([]SGLangLoRAAdapter, len(*in))
		copy(*out, *in)
	}
	if in.TrustRemoteCode != nil {
		in, out := &in.TrustRemoteCode, &out.TrustRemoteCode
		*out = new(bool)
		**out = **in
	}
	if in.SkipTokenizerInit != nil {
		in, out := &in.SkipTokenizerInit, &out.SkipTokenizerInit
		*out = new(bool)
		**out = **in
	}
	if in.HFTokenSecretRef != nil {
		in, out := &in.HFTokenSecretRef, &out.HFTokenSecretRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGLangConfig.
func (in *SGLangConfig) DeepCopy() *SGLangConfig {
	if in == nil {
		return nil
	}
	out := new(SGLangConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGLangLoRAAdapter) DeepCopyInto(out *SGLangLoRAAdapter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGLangLoRAAdapter.
func (in *SGLangLoRAAdapter) DeepCopy() *SGLangLoRAAdapter {
	if in == nil {
		return nil
	}
	out := new(SGLangLoRAAdapter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SGLangSpeculativeConfig) DeepCopyInto(out *SGLangSpeculativeConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.NumSteps != nil {
		in, out := &in.NumSteps, &out.NumSteps
		*out = new(int32)
		**out = **in
	}
	if in.EagleTopK != nil {
		in, out := &in.EagleTopK, &out.EagleTopK
		*out = new(int32)
		**out = **in
	}
	if in.NumDraftTokens != nil {
		in, out := &in.NumDraftTokens, &out.NumDraftTokens
		*out = new(int32)
		**out = **in
	}
	if in.AcceptThresholdSingle != nil {
		in, out := &in.AcceptThresholdSingle, &out.AcceptThresholdSingle
		*out = new(float64)
		**out = **in
	}
	if in.AcceptThresholdAcc != nil {
		in, out := &in.AcceptThresholdAcc, &out.AcceptThresholdAcc
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SGLangSpeculativeConfig.
func (in *SGLangSpeculativeConfig) DeepCopy() *SGLangSpeculativeConfig {
	if in == nil {
		return nil
	}
	out := new(SGLangSpeculativeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOSpec) DeepCopyInto(out *SLOSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOSpec.
func (in *SLOSpec) DeepCopy() *SLOSpec {
	if in == nil {
		return nil
	}
	out := new(SLOSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpeculativeConfig) DeepCopyInto(out *SpeculativeConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.NumSpeculativeTokens != nil {
		in, out := &in.NumSpeculativeTokens, &out.NumSpeculativeTokens
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpeculativeConfig.
func (in *SpeculativeConfig) DeepCopy() *SpeculativeConfig {
	if in == nil {
		return nil
	}
	out := new(SpeculativeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpeculativeDecodingSpec) DeepCopyInto(out *SpeculativeDecodingSpec) {
	*out = *in
	if in.NDraftMax != nil {
		in, out := &in.NDraftMax, &out.NDraftMax
		*out = new(int32)
		**out = **in
	}
	if in.PMin != nil {
		in, out := &in.PMin, &out.PMin
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpeculativeDecodingSpec.
func (in *SpeculativeDecodingSpec) DeepCopy() *SpeculativeDecodingSpec {
	if in == nil {
		return nil
	}
	out := new(SpeculativeDecodingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TGIConfig) DeepCopyInto(out *TGIConfig) {
	*out = *in
	if in.MaxInputLength != nil {
		in, out := &in.MaxInputLength, &out.MaxInputLength
		*out = new(int32)
		**out = **in
	}
	if in.MaxTotalTokens != nil {
		in, out := &in.MaxTotalTokens, &out.MaxTotalTokens
		*out = new(int32)
		**out = **in
	}
	if in.HFTokenSecretRef != nil {
		in, out := &in.HFTokenSecretRef, &out.HFTokenSecretRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TGIConfig.
func (in *TGIConfig) DeepCopy() *TGIConfig {
	if in == nil {
		return nil
	}
	out := new(TGIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamModelAllowlist) DeepCopyInto(out *TeamModelAllowlist) {
	*out = *in
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamModelAllowlist.
func (in *TeamModelAllowlist) DeepCopy() *TeamModelAllowlist {
	if in == nil {
		return nil
	}
	out := new(TeamModelAllowlist)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenCost) DeepCopyInto(out *TokenCost) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenCost.
func (in *TokenCost) DeepCopy() *TokenCost {
	if in == nil {
		return nil
	}
	out := new(TokenCost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLLMConfig) DeepCopyInto(out *VLLMConfig) {
	*out = *in
	if in.TensorParallelSize != nil {
		in, out := &in.TensorParallelSize, &out.TensorParallelSize
		*out = new(int32)
		**out = **in
	}
	if in.PipelineParallelSize != nil {
		in, out := &in.PipelineParallelSize, &out.PipelineParallelSize
		*out = new(int32)
		**out = **in
	}
	if in.MaxModelLen != nil {
		in, out := &in.MaxModelLen, &out.MaxModelLen
		*out = new(int32)
		**out = **in
	}
	if in.KVCacheDtype != nil {
		in, out := &in.KVCacheDtype, &out.KVCacheDtype
		*out = new(string)
		**out = **in
	}
	if in.EnablePrefixCaching != nil {
		in, out := &in.EnablePrefixCaching, &out.EnablePrefixCaching
		*out = new(bool)
		**out = **in
	}
	if in.EnableChunkedPrefill != nil {
		in, out := &in.EnableChunkedPrefill, &out.EnableChunkedPrefill
		*out = new(bool)
		**out = **in
	}
	if in.MaxNumBatchedTokens != nil {
		in, out := &in.MaxNumBatchedTokens, &out.MaxNumBatchedTokens
		*out = new(int32)
		**out = **in
	}
	if in.Speculative != nil {
		in, out := &in.Speculative, &out.Speculative
		*out = new(SpeculativeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.EnableExpertParallel != nil {
		in, out := &in.EnableExpertParallel, &out.EnableExpertParallel
		*out = new(bool)
		**out = **in
	}
	if in.HFTokenSecretRef != nil {
		in, out := &in.HFTokenSecretRef, &out.HFTokenSecretRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.CPUOffloadGB != nil {
		in, out := &in.CPUOffloadGB, &out.CPUOffloadGB
		*out = new(int32)
		**out = **in
	}
	if in.GPUMemoryUtilization != nil {
		in, out := &in.GPUMemoryUtilization, &out.GPUMemoryUtilization
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLLMConfig.
func (in *VLLMConfig) DeepCopy() *VLLMConfig {
	if in == nil {
		return nil
	}
	out := new(VLLMConfig)
	in.DeepCopyInto(out)
	return out
}
